<?xml version="1.0"?>
<!DOCTYPE World [
    <!ELEMENT Item (Country,Tom,Cathy,George,Chang,Jimmy,Sufi,Alex,Mack,Jason,Harry)>
    <!ELEMENT Country (#PCDATA)>
    <!ELEMENT Tom (#PCDATA)>
    <!ELEMENT Cathy (#PCDATA)>
    <!ELEMENT George (#PCDATA)>
    <!ELEMENT Chang (#PCDATA)>
    <!ELEMENT Jimmy (#PCDATA)>
    <!ELEMENT Sufi (#PCDATA)>
    <!ELEMENT Alex (#PCDATA)>
    <!ELEMENT Mack (#PCDATA)>
    <!ELEMENT Jason (#PCDATA)>
    <!ELEMENT Harry (#PCDATA)>
]>
<World>
    <Item>
        <Country>China</Country>
        <Tom>9.8</Tom>
        <Cathy>9.5</Cathy>
        <George>9.4</George>
        <Chang>9.2</Chang>
        <Jimmy>9.0</Jimmy>
        <Sufi>8.5</Sufi>
        <Alex>8.8</Alex>
        <Mack>9.9</Mack>
        <Jason>9.2</Jason>
        <Harry>9.1</Harry>
    </Item>
    <Item>
        <Country>USA</Country>
        <Tom>9.9</Tom>
        <Cathy>9.9</Cathy>
        <George>9.3</George>
        <Chang>8.9</Chang>
        <Jimmy>8.8</Jimmy>
        <Sufi>8.9</Sufi>
        <Alex>8.4</Alex>
        <Mack>9.0</Mack>
        <Jason>9.9</Jason>
        <Harry>9.5</Harry>
    </Item>
    <Item>
        <Country>Japan</Country>
        <Tom>10</Tom>
        <Cathy>9.1</Cathy>
        <George>9.0</George>
        <Chang>9.2</Chang>
        <Jimmy>9.1</Jimmy>
        <Sufi>9.0</Sufi>
        <Alex>9.4</Alex>
        <Mack>9.2</Mack>
        <Jason>8.9</Jason>
        <Harry>8.8</Harry>
    </Item>
    <Item>
        <Country>France</Country>
        <Tom>9.0</Tom>
        <Cathy>8.5</Cathy>
        <George>8.8</George>
        <Chang>9.9</Chang>
        <Jimmy>9.2</Jimmy>
        <Sufi>9.1</Sufi>
        <Alex>9.9</Alex>
        <Mack>9.9</Mack>
        <Jason>9.3</Jason>
        <Harry>8.9</Harry>
    </Item>
    <Item>
        <Country>Russia</Country>
        <Tom>9.8</Tom>
        <Cathy>9.5</Cathy>
        <George>9.4</George>
        <Chang>9.2</Chang>
        <Jimmy>9.1</Jimmy>
        <Sufi>9.0</Sufi>
        <Alex>9.2</Alex>
        <Mack>9.1</Mack>
        <Jason>9.1</Jason>
        <Harry>9.0</Harry>
    </Item>
    <Item>
        <Country>Italy</Country>
        <Tom>9.9</Tom>
        <Cathy>9.9</Cathy>
        <George>9.3</George>
        <Chang>8.9</Chang>
        <Jimmy>8.8</Jimmy>
        <Sufi>9.0</Sufi>
        <Alex>9.4</Alex>
        <Mack>9.2</Mack>
        <Jason>8.9</Jason>
        <Harry>8.2</Harry>
    </Item>
    <Item>
        <Country>Australia</Country>
        <Tom>9.0</Tom>
        <Cathy>8.5</Cathy>
        <George>8.8</George>
        <Chang>9.9</Chang>
        <Jimmy>9.2</Jimmy>
        <Sufi>9.1</Sufi>
        <Alex>9.4</Alex>
        <Mack>9.2</Mack>
        <Jason>9.1</Jason>
        <Harry>9.1</Harry>
    </Item>
    <Item>
        <Country>Germany</Country>
        <Tom>9.8</Tom>
        <Cathy>9.5</Cathy>
        <George>9.4</George>
        <Chang>9.2</Chang>
        <Jimmy>9.1</Jimmy>
        <Sufi>9.5</Sufi>
        <Alex>9.4</Alex>
        <Mack>9.2</Mack>
        <Jason>9.0</Jason>
        <Harry>8.5</Harry>
    </Item>
    <Item>
        <Country>Taiwan</Country>
        <Tom>9.9</Tom>
        <Cathy>9.3</Cathy>
        <George>8.9</George>
        <Chang>8.8</Chang>
        <Jimmy>8.9</Jimmy>
        <Sufi>8.4</Sufi>
        <Alex>9.0</Alex>
        <Mack>9.1</Mack>
        <Jason>9.0</Jason>
        <Harry>9.2</Harry>
    </Item>
</World>